### ISSUE TITLE
Scalable text rendering library in Unity

### ISSUE THREAD

**Issue by noisiak** [zwcloud/ImGui#2]
Hello there! I recently found this repo. I wondered if is possible to implement this on Unity as a library. I am particularly interested in the text rendering system (came here from the Medium "Easy Scalable Text Rendering on the GPU" article).

**Comment by zwcloud** [comment]
@noisiak Sure. All needed are a special shader like [this](https://github.com/zwcloud/ImGui/blob/7d9aa1fbdf6bd19c5c33d0c8493943d3988d2d06/src/ImGui/OSImplentation/Windows/Win32OpenGLRenderer.cs#L86) and [the glyph contours](https://github.com/zwcloud/ImGui/blob/7b39e828ee6e20cfc1b15bb173378902c360146d/src/ImGui/DrawList/Text/GlyphCache.cs#L15) consisting of polygons and quadratic curve segments.

**Comment by noisiak** [comment]
Hey thanks. I will explore these. The shader looks very complex and interesting, I am guessing (not an expert here) that I need to create a shader file in unity and transfer the shader code to that file and later create or adapt the glyph contours .cs script to work in Unity.
